config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get '/lock_out' => 'lock_out#index'
post '/lock_out/lock/:year/:month' => 'lock_out#lock', :as => :lock_date
post '/lock_out/unlock/:year/:month' => 'lock_out#unlock', :as => :unlock_date

app/models/lock_out_date.rb
class LockOutDate < ActiveRecord::Base
  unloadable

  def <=>(other)
    if self.month == other.month &&
      self.year == other.year
      return 0
    end

    if self.year < other.year
      return -1
    end

    if self.month < other.month
      return -1
    end

    1
  end
end

app/controllers/lock_out_controller.rb
class LockOutController < ApplicationController
  unloadable
  before_filter :authorize_global
  before_filter :find_or_create_date, :only => [:lock, :unlock]

  def index
    now = Time.now
    @dates = []

    # generate last 7 months
    7.times do |i|
      now = now - 1.month
      @dates << LockOutDate.
        where(:month => now.month).
        where(:year  => now.year).
        first_or_create
    end

    @dates.sort! { |x,y| y <=> x }
  end

  def lock
    @date.locked = true
    if @date.save
      redirect_to lock_out_path, :notice => "Dates were locked successfully."
    else
      redirect_to lock_out_path, :error => "The dates could not be locked."
    end
  end

  def unlock
    @date.locked = false
    if @date.save
      redirect_to lock_out_path, :notice => "Dates were unlocked successfully."
    else
      redirect_to lock_out_path, :error => "The dates could not be unlocked."
    end
  end

  private

  def find_or_create_date
    @date = LockOutDate.
      where(:month => params[:month], :year => params[:year]).
      first_or_create!
  end

end

app/helpers/lock_out_helper.rb
module LockOutHelper
end

app/views/lock_out/index.html.erb
<h2>Time sheet lock out dates</h2>

<table class="list">
  <tr>
    <th>Year</th>
    <th>Month</th>
    <th>Locked</th>
    <th></th>
  </tr>
  <% @dates.each do |date| %>
  <tr>
    <td><%= date.year %></td>
    <td><%= date.month %></td>
    <td><%= image_tag(date.locked ? 'true.png' : 'exclamation.png', :style => "vertical-align:bottom;" )%></td>
    <td class='buttons'>
      <%= link_to((date.locked ? 'Unlock' : 'Lock'), (date.locked ? unlock_date_path(:year => date.year, :month => date.month) : lock_date_path(:year => date.year, :month => date.month) ), :method => :post) %>
    </td>
  </tr>
  <% end %>
</table>

app/views/settings/_lock_out_settings.html.erb
<p>
  <label for="lock_out_day">Day of current month to lock previous month</label>
  <%= text_field_tag 'settings[lock_out_day]', @settings['lock_out_day'] %>
</p>